<?php declare(strict_types=1);

namespace EventCandy\LabelMe;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\InstallContext;
use Shopware\Core\Framework\Plugin\Context\UninstallContext;

class EventCandyLabelMe extends Plugin
{

    public function install(InstallContext $installContext): void
    {
        parent::install($installContext); // TODO: Change the autogenerated stub
    }


    public function uninstall(UninstallContext $uninstallContext): void
    {
        if ($uninstallContext->keepUserData()) {
            return;
        }

//        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_label');
//        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_event');
//        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_candy_package');
//        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_package');
//        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_candy');
    }
}
