<?php declare(strict_types=1);

namespace EventCandy\LabelMe;

use Doctrine\DBAL\Connection;
use Shopware\Core\Framework\Plugin;
use Shopware\Core\Framework\Plugin\Context\ActivateContext;
use Shopware\Core\Framework\Plugin\Context\InstallContext;
use Shopware\Core\Framework\Plugin\Context\UninstallContext;

class EventCandyLabelMe extends Plugin
{

    /**
     * @var DemoDataService
     */
    private $demoDataService;

    public function activate(ActivateContext $context): void
    {

        $connection = $this->container->get(Connection::class);

        $sql = "select count(*) from eclm_event";
        $result = $connection->fetchArray($sql);
        // data should exist, quit migration
        if ($result[0] != 0) {
            return;
        }

        $this->demoDataService->generate($context->getContext());
    }


    public function install(InstallContext $installContext): void
    {
        parent::install($installContext); // TODO: Change the autogenerated stub

    }


    public function uninstall(UninstallContext $uninstallContext): void
    {
        if ($uninstallContext->keepUserData()) {
            return;
        }

        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_label');
        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_event');
        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_candy_package');
        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_package');
        $this->container->get(Connection::class)->exec('DROP TABLE IF EXISTS eclm_candy');
    }


    /**
     * @required
     */
    public function setDemoDataService(DemoDataService $demoDataService): void
    {
        $this->demoDataService = $demoDataService;
    }
}
